export interface CourtInfo {
  type: "Superior" | "Circuit";
  divisions?: number;
}

export interface CountyData {
  name: string;
  number: number;
  courts: CourtInfo[];
}

export const INDIANA_COUNTIES: CountyData[] = [
  { name: "Adams", number: 1, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Allen", number: 2, courts: [{ type: "Superior", divisions: 9 }, { type: "Circuit" }] },
  { name: "Bartholomew", number: 3, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Benton", number: 4, courts: [{ type: "Circuit" }] },
  { name: "Blackford", number: 5, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Boone", number: 6, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Brown", number: 7, courts: [{ type: "Circuit" }] },
  { name: "Carroll", number: 8, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Cass", number: 9, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Clark", number: 10, courts: [{ type: "Circuit" }] },
  { name: "Clay", number: 11, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Clinton", number: 12, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Crawford", number: 13, courts: [{ type: "Circuit" }] },
  { name: "Daviess", number: 14, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Dearborn", number: 15, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Decatur", number: 16, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "DeKalb", number: 17, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Delaware", number: 18, courts: [{ type: "Circuit" }] },
  { name: "Dubois", number: 19, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Elkhart", number: 20, courts: [{ type: "Superior", divisions: 6 }, { type: "Circuit" }] },
  { name: "Fayette", number: 21, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Floyd", number: 22, courts: [{ type: "Superior", divisions: 3 }, { type: "Circuit" }] },
  { name: "Fountain", number: 23, courts: [{ type: "Circuit" }] },
  { name: "Franklin", number: 24, courts: [{ type: "Circuit" }] },
  { name: "Fulton", number: 25, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Gibson", number: 26, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Grant", number: 27, courts: [{ type: "Superior", divisions: 3 }, { type: "Circuit" }] },
  { name: "Greene", number: 28, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Hamilton", number: 29, courts: [{ type: "Superior", divisions: 7 }, { type: "Circuit" }] },
  { name: "Hancock", number: 30, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Harrison", number: 31, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Hendricks", number: 32, courts: [{ type: "Superior", divisions: 5 }, { type: "Circuit" }] },
  { name: "Henry", number: 33, courts: [{ type: "Circuit" }] },
  { name: "Howard", number: 34, courts: [{ type: "Superior", divisions: 4 }, { type: "Circuit" }] },
  { name: "Huntington", number: 35, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Jackson", number: 36, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Jasper", number: 37, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Jay", number: 38, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Jefferson", number: 39, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Jennings", number: 40, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Johnson", number: 41, courts: [{ type: "Superior", divisions: 4 }, { type: "Circuit" }] },
  { name: "Knox", number: 42, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Kosciusko", number: 43, courts: [{ type: "Superior", divisions: 4 }, { type: "Circuit" }] },
  { name: "LaGrange", number: 44, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Lake", number: 45, courts: [{ type: "Superior", divisions: 16 }, { type: "Circuit" }] },
  { name: "LaPorte", number: 46, courts: [{ type: "Superior", divisions: 4 }, { type: "Circuit" }] },
  { name: "Lawrence", number: 47, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Madison", number: 48, courts: [{ type: "Circuit" }] },
  { name: "Marion", number: 49, courts: [{ type: "Superior", divisions: 36 }, { type: "Circuit" }] },
  { name: "Marshall", number: 50, courts: [{ type: "Superior", divisions: 3 }, { type: "Circuit" }] },
  { name: "Martin", number: 51, courts: [{ type: "Circuit" }] },
  { name: "Miami", number: 52, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Monroe", number: 53, courts: [{ type: "Circuit" }] },
  { name: "Montgomery", number: 54, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Morgan", number: 55, courts: [{ type: "Superior", divisions: 3 }, { type: "Circuit" }] },
  { name: "Newton", number: 56, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Noble", number: 57, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Ohio", number: 58, courts: [{ type: "Circuit" }] },
  { name: "Orange", number: 59, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Owen", number: 60, courts: [{ type: "Circuit" }] },
  { name: "Parke", number: 61, courts: [{ type: "Circuit" }] },
  { name: "Perry", number: 62, courts: [{ type: "Circuit" }] },
  { name: "Pike", number: 63, courts: [{ type: "Circuit" }] },
  { name: "Porter", number: 64, courts: [{ type: "Superior", divisions: 6 }, { type: "Circuit" }] },
  { name: "Posey", number: 65, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Pulaski", number: 66, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Putnam", number: 67, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Randolph", number: 68, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Ripley", number: 69, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Rush", number: 70, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "St. Joseph", number: 71, courts: [{ type: "Superior", divisions: 8 }, { type: "Circuit" }] },
  { name: "Scott", number: 72, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Shelby", number: 73, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Spencer", number: 74, courts: [{ type: "Circuit" }] },
  { name: "Starke", number: 75, courts: [{ type: "Circuit" }] },
  { name: "Steuben", number: 76, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Sullivan", number: 77, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Switzerland", number: 78, courts: [{ type: "Circuit" }] },
  { name: "Tippecanoe", number: 79, courts: [{ type: "Superior", divisions: 7 }, { type: "Circuit" }] },
  { name: "Tipton", number: 80, courts: [{ type: "Circuit" }] },
  { name: "Union", number: 81, courts: [{ type: "Circuit" }] },
  { name: "Vanderburgh", number: 82, courts: [{ type: "Superior", divisions: 7 }, { type: "Circuit" }] },
  { name: "Vermillion", number: 83, courts: [{ type: "Circuit" }] },
  { name: "Vigo", number: 84, courts: [{ type: "Superior", divisions: 6 }, { type: "Circuit" }] },
  { name: "Wabash", number: 85, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Warren", number: 86, courts: [{ type: "Circuit" }] },
  { name: "Warrick", number: 87, courts: [{ type: "Superior", divisions: 2 }, { type: "Circuit" }] },
  { name: "Washington", number: 88, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Wayne", number: 89, courts: [{ type: "Superior", divisions: 3 }, { type: "Circuit" }] },
  { name: "Wells", number: 90, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "White", number: 91, courts: [{ type: "Superior" }, { type: "Circuit" }] },
  { name: "Whitley", number: 92, courts: [{ type: "Superior" }, { type: "Circuit" }] },
];

export function getCourtsForCounty(countyName: string): string[] {
  const county = INDIANA_COUNTIES.find((c) => c.name === countyName);
  if (!county) return [];

  const courts: string[] = [];
  for (const court of county.courts) {
    if (court.divisions && court.divisions > 1) {
      for (let i = 1; i <= court.divisions; i++) {
        courts.push(`${county.name} ${court.type} Court ${i}`);
      }
    } else {
      courts.push(`${county.name} ${court.type} Court`);
    }
  }
  return courts;
}

/**
 * Generate the cause number prefix for a given court name.
 * Format: {countyNumber}{courtTypeLetter}{divisionNumber}-
 * Superior = D, Circuit = C. Division is zero-padded to 2 digits.
 * Examples: "Wayne Superior Court 3" → "89D03-", "Randolph Circuit Court" → "68C01-"
 */
export function getCauseNumberPrefix(courtName: string): string {
  // Parse: "{County} {Superior|Circuit} Court {division?}"
  const match = courtName.match(/^(.+?)\s+(Superior|Circuit)\s+Court\s*(\d+)?$/);
  if (!match) return "";

  const [, countyName, courtType, divisionStr] = match;
  const county = INDIANA_COUNTIES.find((c) => c.name === countyName);
  if (!county) return "";

  const countyNum = String(county.number).padStart(2, "0");
  const typeLetter = courtType === "Superior" ? "D" : "C";
  const division = divisionStr ? String(parseInt(divisionStr)).padStart(2, "0") : "01";

  return `${countyNum}${typeLetter}${division}-`;
}

/** Judge names keyed by court name (e.g. "Wayne Superior Court 3") */
const COURT_JUDGES: Record<string, string> = {
  "Adams Superior Court": "Samuel K. Conrad",
  "Adams Circuit Court": "Chad E. Kukelhan",
  "Allen Superior Court 1": "Andrew S. Williams",
  "Allen Superior Court 2": "Craig J. Bobay",
  "Allen Superior Court 3": "Jennifer L. DeGroote",
  "Allen Superior Court 4": "Steven O. Godfrey",
  "Allen Superior Court 5": "Frances C. Gull",
  "Allen Superior Court 6": "David M. Zent",
  "Allen Superior Court 7": "Brent A. Ecenbarger",
  "Allen Superior Court 8": "Lori K. Morgan",
  "Allen Superior Court 9": "Jason C. Custer",
  "Allen Circuit Court": "Ashley N. Hand",
  "Bartholomew Superior Court 1": "James Worton",
  "Bartholomew Superior Court 2": "Jonathan Rohde",
  "Bartholomew Circuit Court": "Kelly S. Benjamin",
  "Benton Circuit Court": "",
  "Blackford Superior Court": "",
  "Blackford Circuit Court": "Brian Bade",
  "Boone Superior Court 1": "Matthew C. Kincaid",
  "Boone Superior Court 2": "Bruce Petit",
  "Boone Circuit Court": "J. Jeffrey Edens",
  "Brown Circuit Court": "Mary Wertz",
  "Carroll Superior Court": "Troy Hawkins",
  "Carroll Circuit Court": "Shane Evans",
  "Cass Superior Court 1": "Lisa Swaim",
  "Cass Superior Court 2": "James K. Muehlhausen",
  "Cass Circuit Court": "",
  "Clark Circuit Court": "",
  "Clay Superior Court": "Bob Pell",
  "Clay Circuit Court": "David Thomas",
  "Clinton Superior Court": "Justin Hunter",
  "Clinton Circuit Court": "Bradley K. Mohler",
  "Crawford Circuit Court": "Justin Mills",
  "Daviess Superior Court": "Daniel S. Murrie",
  "Daviess Circuit Court": "Gregory Smith",
  "Dearborn Superior Court 1": "Jonathan N. Cleary",
  "Dearborn Superior Court 2": "Sally A. McLaughlin",
  "Dearborn Circuit Court": "F. Aaron Negangard",
  "Decatur Superior Court": "Matthew D. Bailey",
  "Decatur Circuit Court": "Timothy B. Day",
  "DeKalb Superior Court 1": "Adam C. Squiller",
  "DeKalb Superior Court 2": "Kurt B. Grimm",
  "DeKalb Circuit Court": "Monte L. Brown",
  "Delaware Circuit Court": "",
  "Dubois Superior Court": "Anthony D. Quinn",
  "Dubois Circuit Court": "Nathan A. Verkamp",
  "Elkhart Superior Court 1": "Kristine A. Osterday",
  "Elkhart Superior Court 2": "Andrew M. Hicks",
  "Elkhart Superior Court 3": "Teresa L. Cataldo",
  "Elkhart Superior Court 4": "Elizabeth A. Bellin",
  "Elkhart Superior Court 5": "Christopher J. Spataro",
  "Elkhart Superior Court 6": "David C. Bonfiglio",
  "Elkhart Circuit Court": "Michael A. Christofeno",
  "Fayette Superior Court": "",
  "Fayette Circuit Court": "Hubert Branstetter Jr.",
  "Floyd Superior Court 1": "Carrie K. Stiller",
  "Floyd Superior Court 2": "",
  "Floyd Superior Court 3": "Maria D. Granger",
  "Floyd Circuit Court": "Justin Brown",
  "Fountain Circuit Court": "Stephanie S. Campbell",
  "Franklin Circuit Court": "",
  "Fulton Superior Court": "Wayne E. Steele",
  "Fulton Circuit Court": "",
  "Gibson Superior Court": "Robert Krieg",
  "Gibson Circuit Court": "",
  "Grant Superior Court 1": "Jeffrey D. Todd",
  "Grant Superior Court 2": "Bridget N. Foust",
  "Grant Superior Court 3": "Jason McVicker",
  "Grant Circuit Court": "Mark E. Spitzer",
  "Greene Superior Court": "Dena A. Martin",
  "Greene Circuit Court": "Erik C. Allen",
  "Hamilton Superior Court 1": "Michael A. Casati",
  "Hamilton Superior Court 2": "Jonathan M. Brown",
  "Hamilton Superior Court 3": "William J. Hughes",
  "Hamilton Superior Court 4": "J. Richard Campbell",
  "Hamilton Superior Court 5": "David K. Najjar",
  "Hamilton Superior Court 6": "Stephenie K. Gookins",
  "Hamilton Superior Court 7": "Darren J. Murphy",
  "Hamilton Circuit Court": "Andrew R. Bloch",
  "Hancock Superior Court 1": "DJ Davis",
  "Hancock Superior Court 2": "Dan E. Marshall",
  "Hancock Circuit Court": "Scott Sirk",
  "Harrison Superior Court": "Joseph L. Claypool",
  "Harrison Circuit Court": "John T. Evans",
  "Hendricks Superior Court 1": "Robert Freese",
  "Hendricks Superior Court 2": "Rhett Stuard",
  "Hendricks Superior Court 3": "Kathryn M. Kuehn",
  "Hendricks Superior Court 4": "Stephenie D. LeMay-Luken",
  "Hendricks Superior Court 5": "",
  "Hendricks Circuit Court": "Daniel Zielinski",
  "Henry Circuit Court": "",
  "Howard Superior Court 1": "George Hopkins Menges III",
  "Howard Superior Court 2": "",
  "Howard Superior Court 3": "",
  "Howard Superior Court 4": "",
  "Howard Circuit Court": "",
  "Huntington Superior Court": "Jennifer Newton",
  "Huntington Circuit Court": "Davin G. Smith",
  "Jackson Superior Court 1": "Amy Marie Travis",
  "Jackson Superior Court 2": "Bruce MacTavish",
  "Jackson Circuit Court": "Richard Poynter",
  "Jasper Superior Court": "Russell D. Bailey",
  "Jasper Circuit Court": "Emily Waddle",
  "Jay Superior Court": "Gail Dues",
  "Jay Circuit Court": "Brian D. Hutchison",
  "Jefferson Superior Court": "",
  "Jefferson Circuit Court": "",
  "Jennings Superior Court": "",
  "Jennings Circuit Court": "Murielle Bright",
  "Johnson Superior Court 1": "Brandi Kirkendall",
  "Johnson Superior Court 2": "Peter Nugent",
  "Johnson Superior Court 3": "Douglas Cummins",
  "Johnson Superior Court 4": "Marla Clark",
  "Johnson Circuit Court": "Andrew Roesner",
  "Knox Superior Court 1": "Gara U. Lee",
  "Knox Superior Court 2": "Brian Johnson",
  "Knox Circuit Court": "Monica C. Gilmore",
  "Kosciusko Superior Court 1": "Karin McGrath",
  "Kosciusko Superior Court 2": "Torrey Bauer",
  "Kosciusko Superior Court 3": "Chad M. Miner",
  "Kosciusko Superior Court 4": "Christopher D. Kehler",
  "Kosciusko Circuit Court": "Matt Buehler",
  "LaGrange Superior Court": "Lisa Bowen-Slaven",
  "LaGrange Circuit Court": "William R. Walz IV",
  "Lake Superior Court 1": "John M. Sedia",
  "Lake Superior Court 2": "Calvin D. Hawkins",
  "Lake Superior Court 3": "Thomas P. Hallett",
  "Lake Superior Court 4": "",
  "Lake Superior Court 5": "Daniel W. Burke",
  "Lake Superior Court 6": "Rehana R. Adat-Lopez",
  "Lake Superior Court 7": "Bruce D. Parent",
  "Lake Superior Court 8": "Salvador Vasquez",
  "Lake Superior Court 9": "Clarence D. Murray",
  "Lake Superior Court 10": "Diane Ross Boswell",
  "Lake Superior Court 11": "Samuel L. Cappas",
  "Lake Superior Court 12": "Nicholas J. Schiralli",
  "Lake Superior Court 13": "Sheila M. Moss",
  "Lake Superior Court 14": "Julie N. Cantrell",
  "Lake Superior Court 15": "Stephen A. Tyler",
  "Lake Superior Court 16": "",
  "Lake Circuit Court": "Marissa McDermott",
  "LaPorte Superior Court 1": "Jaime M. Oss",
  "LaPorte Superior Court 2": "Richard R. Stalbrink Jr.",
  "LaPorte Superior Court 3": "Jeffrey L. Thorne",
  "LaPorte Superior Court 4": "Greta Stirling Friedman",
  "LaPorte Circuit Court": "Julianne K. Havens",
  "Lawrence Superior Court 1": "",
  "Lawrence Superior Court 2": "",
  "Lawrence Circuit Court": "",
  "Madison Circuit Court": "",
  "Marion Superior Court 1": "",
  "Marion Superior Court 2": "",
  "Marion Superior Court 3": "",
  "Marion Superior Court 4": "",
  "Marion Superior Court 5": "John M.T. Chavis II",
  "Marion Superior Court 6": "",
  "Marion Superior Court 7": "Marshelle Broadwell",
  "Marion Superior Court 8": "David Certo",
  "Marion Superior Court 9": "",
  "Marion Superior Court 10": "",
  "Marion Superior Court 11": "Richard Blaiklock",
  "Marion Superior Court 12": "PJ Dietrick",
  "Marion Superior Court 13": "",
  "Marion Superior Court 14": "",
  "Marion Superior Court 15": "",
  "Marion Superior Court 16": "Stephen Creason",
  "Marion Superior Court 17": "",
  "Marion Superior Court 18": "",
  "Marion Superior Court 19": "",
  "Marion Superior Court 20": "",
  "Marion Superior Court 21": "",
  "Marion Superior Court 22": "",
  "Marion Superior Court 23": "",
  "Marion Superior Court 24": "",
  "Marion Superior Court 25": "",
  "Marion Superior Court 26": "",
  "Marion Superior Court 27": "Angela Davis",
  "Marion Superior Court 28": "",
  "Marion Superior Court 29": "",
  "Marion Superior Court 30": "",
  "Marion Superior Court 31": "",
  "Marion Superior Court 32": "",
  "Marion Superior Court 33": "",
  "Marion Superior Court 34": "",
  "Marion Superior Court 35": "",
  "Marion Superior Court 36": "",
  "Marion Circuit Court": "Tiffany Vivo",
  "Marshall Superior Court 1": "Tami L. Napier",
  "Marshall Superior Court 2": "Matthew T. Aldridge",
  "Marshall Superior Court 3": "Matthew Sarber",
  "Marshall Circuit Court": "Janette E. Surrisi",
  "Martin Circuit Court": "Isha Wright-Ryan",
  "Miami Superior Court 1": "David Grund",
  "Miami Superior Court 2": "",
  "Miami Circuit Court": "Timothy P. Spahr",
  "Monroe Circuit Court": "",
  "Montgomery Superior Court 1": "Heather Barajas",
  "Montgomery Superior Court 2": "Daniel Petrie",
  "Montgomery Circuit Court": "Darren Chadd",
  "Morgan Superior Court 1": "Dakota R. VanLeeuwen",
  "Morgan Superior Court 2": "Brian H. Williams",
  "Morgan Superior Court 3": "Sara A. Dungan",
  "Morgan Circuit Court": "Matthew G. Hanson",
  "Newton Superior Court": "Daniel J. Molter",
  "Newton Circuit Court": "Jeryl F. Leach",
  "Noble Superior Court 1": "",
  "Noble Superior Court 2": "",
  "Noble Circuit Court": "",
  "Ohio Circuit Court": "F. Aaron Negangard",
  "Orange Superior Court": "",
  "Orange Circuit Court": "Steve Owen",
  "Owen Circuit Court": "",
  "Parke Circuit Court": "Sam Swaim",
  "Perry Circuit Court": "Lucy Goffinet",
  "Pike Circuit Court": "Evan Biesterveld",
  "Porter Superior Court 1": "Michael A. Fish",
  "Porter Superior Court 2": "Jeffrey Clymer",
  "Porter Superior Court 3": "Michael Drenth",
  "Porter Superior Court 4": "Christopher Buckley",
  "Porter Superior Court 5": "Mary DeBoer",
  "Porter Superior Court 6": "Jeffrey L. Thode",
  "Porter Circuit Court": "Rebecca Buitendorp",
  "Posey Superior Court": "Travis Clowers",
  "Posey Circuit Court": "Craig Goedde",
  "Pulaski Superior Court": "Crystal A. Brucker Kocher",
  "Pulaski Circuit Court": "",
  "Putnam Superior Court": "",
  "Putnam Circuit Court": "Matthew L. Headley",
  "Randolph Superior Court": "",
  "Randolph Circuit Court": "Jay L. Toney",
  "Ripley Superior Court": "",
  "Ripley Circuit Court": "Ryan J. King",
  "Rush Superior Court": "Leigh S. Morning",
  "Rush Circuit Court": "Brian Hill",
  "St. Joseph Superior Court 1": "Christopher Fronk",
  "St. Joseph Superior Court 2": "David L. Francisco",
  "St. Joseph Superior Court 3": "Jeffery Sanford",
  "St. Joseph Superior Court 4": "Stephanie Steele",
  "St. Joseph Superior Court 5": "Jenny Pitts Manier",
  "St. Joseph Superior Court 6": "Jamie C. Woods",
  "St. Joseph Superior Court 7": "Mark J. Telloyan",
  "St. Joseph Superior Court 8": "Elizabeth C. Hurley",
  "St. Joseph Circuit Court": "John E. Broden",
  "Scott Superior Court": "Marsha Owens Howser",
  "Scott Circuit Court": "Jason M. Mount",
  "Shelby Superior Court 1": "Raymond K. Apsley",
  "Shelby Superior Court 2": "",
  "Shelby Circuit Court": "Trent Meltzer",
  "Spencer Circuit Court": "Jon Dartt",
  "Starke Circuit Court": "Kim Hall",
  "Steuben Superior Court": "William Fee",
  "Steuben Circuit Court": "Jeremy Musser",
  "Sullivan Superior Court": "Hugh R. Hunt",
  "Sullivan Circuit Court": "Robert E. Hunley II",
  "Switzerland Circuit Court": "W. Gregory Coy",
  "Tippecanoe Superior Court 1": "Randy Williams",
  "Tippecanoe Superior Court 2": "Steve Meyer",
  "Tippecanoe Superior Court 3": "Faith Graham",
  "Tippecanoe Superior Court 4": "Mathew Sandy",
  "Tippecanoe Superior Court 5": "Kristen McVey",
  "Tippecanoe Superior Court 6": "Michael Morrissey",
  "Tippecanoe Superior Court 7": "Daniel Moore",
  "Tippecanoe Circuit Court": "Sean Persin",
  "Tipton Circuit Court": "Thomas R. Lett",
  "Union Circuit Court": "",
  "Vanderburgh Superior Court 1": "Jillian N. Kratochvil",
  "Vanderburgh Superior Court 2": "Robert J. Pigman",
  "Vanderburgh Superior Court 3": "Mary Margaret Lloyd",
  "Vanderburgh Superior Court 4": "Wayne S. Trockman",
  "Vanderburgh Superior Court 5": "Thomas A. Massey",
  "Vanderburgh Superior Court 6": "Leslie C. Shively",
  "Vanderburgh Superior Court 7": "Gary J. Schutte",
  "Vanderburgh Circuit Court": "Ryan D. Hatfield",
  "Vermillion Circuit Court": "Bruce V. Stengel",
  "Vigo Superior Court 1": "Charles Johnson",
  "Vigo Superior Court 2": "Lakshmi Reddy",
  "Vigo Superior Court 3": "Sarah K. Mullican",
  "Vigo Superior Court 4": "Christopher A. Newton",
  "Vigo Superior Court 5": "Matthew Sheehan",
  "Vigo Superior Court 6": "Michael J. Lewis",
  "Vigo Circuit Court": "Sarah K. Mullican",
  "Wabash Superior Court": "Christopher M. Goff",
  "Wabash Circuit Court": "",
  "Warren Circuit Court": "Hunter J. Reece",
  "Warrick Superior Court 1": "",
  "Warrick Superior Court 2": "Brett M. Roy",
  "Warrick Circuit Court": "Greg A. Granger",
  "Washington Superior Court": "",
  "Washington Circuit Court": "Larry Medlock",
  "Wayne Superior Court 1": "Charles Todd Jr.",
  "Wayne Superior Court 2": "",
  "Wayne Superior Court 3": "Mark Cox",
  "Wayne Circuit Court": "Gregory A. Horn",
  "Wells Superior Court": "",
  "Wells Circuit Court": "Kenton Kiracofe",
  "White Superior Court": "Brad Woolley",
  "White Circuit Court": "Jason A. Thompson",
  "Whitley Superior Court": "Douglas M. Fahl",
  "Whitley Circuit Court": "Matthew J. Rentschler",
};

/**
 * Look up the judge name for a given court.
 * Returns the judge's name or empty string if unknown.
 */
export function getJudgeForCourt(courtName: string): string {
  return COURT_JUDGES[courtName] ?? "";
}
